services:
- docker
script:
- docker-compose -f docker-compose.test.yml up --abort-on-container-exit
before-_deploy:
- pip install --user awscli
- pip install --user awsebcli
- export PATH=$PATH:$HOME/.local/bin
deploy:
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master
  skip_cleanup: true
